CREATE UNIQUE INDEX IF NOT EXISTS idx_rooms_room_id ON rooms(room_id);

ALTER TABLE rooms ADD COLUMN IF NOT EXISTS room_type TEXT;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'telegram';
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS last_seen_at TEXT;

ALTER TABLE files ADD COLUMN IF NOT EXISTS telegram_file_id TEXT;
ALTER TABLE files ADD COLUMN IF NOT EXISTS telegram_file_unique_id TEXT;
ALTER TABLE files ADD COLUMN IF NOT EXISTS uploader_id TEXT;
ALTER TABLE files ADD COLUMN IF NOT EXISTS uploader_name TEXT;
ALTER TABLE files ADD COLUMN IF NOT EXISTS file_type TEXT;
ALTER TABLE files ADD COLUMN IF NOT EXISTS mime_type TEXT;
ALTER TABLE files ADD COLUMN IF NOT EXISTS file_size INTEGER DEFAULT 0;
ALTER TABLE files ADD COLUMN IF NOT EXISTS extracted_text TEXT;
ALTER TABLE files ADD COLUMN IF NOT EXISTS tags_json TEXT;

CREATE INDEX IF NOT EXISTS idx_files_unique_id ON files(telegram_file_unique_id);
